### ISSUE TITLE
Add navigation buttons to 'About' and 'How To Play' 

### ISSUE THREAD

**Issue by kajgrant** [ConorMurphy21/StrikeOrSike#155]
- The 'About' and 'How To Play' pages should have a navigation button somewhere to navigate to the home page
- The user should be able to click the button and return to the main page
- Button should be either an  intuitive home icon or an 'X' symbol

**Comment by ConorMurphy21** [comment]
Assigning @jengu288 as a reviewer to ensure the UI/UX does not negatively impact the aestetic
