### ISSUE TITLE
Bug: Hitting back button does not clear player list

### ISSUE THREAD

**Issue by maheeppartap** [ConorMurphy21/StrikeOrSike#20]
Description: Hitting the back button after you create the room should be clearing the player list. It does not. As a result, if you hit the back button and create a new room, all previous players appear in the new room.
Fix:  Add a new mutation to the client that automatically clears the player list, instead of just appending it to the list like an idiot (Conor)

**Comment by ConorMurphy21** [comment]
Fixed
